Repository googleapis/ruby-spanner-activerecord, pull requests merged in 2020-11, with the labels that each got.

#46 test: remove non-existant checks
  .github/sync-repo-settings.yaml
Labels: api: spanner, cla: yes

#43 Fix draft version of URLs on README.md
  README.md
Labels: api: spanner, cla: yes, kokoro:force-run, kokoro:run

#45 Improve settings and documents to run RuboCop locally
  .rubocop.yml
  CONTRIBUTING.md
Labels: cla: yes

#50 Add basic test on GitHub Actions
  .github/workflows/ci.yaml
Labels: api: spanner, cla: yes

#51 Enable and improve `bin/console` for easier gem development
  bin/console
Labels: api: spanner, cla: yes

#49 add rubocop workflow
  .github/workflows/rubocop.yaml
  README.md
  activerecord-spanner-adapter.gemspec
Labels: api: spanner, cla: yes
