Repository googleapis/ruby-spanner-activerecord, pull requests merged in 2021-12, with the labels that each got.

#143 chore: cast COLUMN_DEFAULT to STRING
  lib/activerecord_spanner_adapter/information_schema.rb
  test/activerecord_spanner_adapter/information_schema_test.rb
  test/activerecord_spanner_interleaved_table/model_helper.rb
  test/activerecord_spanner_mock_server/model_helper.rb
  test/migrations_with_mock_server/migrations_with_mock_server_test.rb
Labels: api: spanner, cla: yes

#144 chore: remove sample for interleaved table
  CHANGELOG.md
  README.md
  examples/snippets/interleaved-tables/README.md
  examples/snippets/interleaved-tables/Rakefile
  examples/snippets/interleaved-tables/application.rb
  examples/snippets/interleaved-tables/config/database.yml
  examples/snippets/interleaved-tables/db/migrate/01_create_tables.rb
  examples/snippets/interleaved-tables/db/schema.rb
  examples/snippets/interleaved-tables/db/seeds.rb
  examples/snippets/interleaved-tables/models/album.rb
  examples/snippets/interleaved-tables/models/singer.rb
  examples/snippets/interleaved-tables/models/track.rb
Labels: api: spanner, cla: yes, samples

#145 chore: create a GA release as v1.0.0
  README.md
Labels: api: spanner

#146 feat: release 1.0.0
  README.md
Labels: api: spanner

#149 chore: Fix default branch in a bunch of workflow configs
  .github/sync-repo-settings.yaml
  .github/workflows/acceptance-tests-on-emulator.yaml
  .github/workflows/acceptance-tests-on-production.yaml
  .github/workflows/ci.yaml
  .github/workflows/release-please-label.yml
  .github/workflows/rubocop.yaml
  CONTRIBUTING.md
  README.md
Labels: api: spanner

#150 chore: auto-assign issues to Spanner owner
  .github/blunderbuss.yml
Labels: api: spanner

#153 docs: fix a couple of minor formatting issues
  examples/rails/README.md
Labels: api: spanner
